[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "quatrex"
authors = [
    { name = "Alexander Maeder", email = "almaeder@iis.ee.ethz.ch" },
    { name = "Alexandros Nikolaos Ziogas", email = "alziogas@iis.ee.ethz.ch" },
    { name = "Anders Winka", email = "awinka@iis.ee.ethz.ch" },
    { name = "Jiang Cao", email = "jiang.cao@iis.ee.ethz.ch" },
    { name = "Leonard Deuschle", email = "dleonard@iis.ee.ethz.ch" },
    { name = "Mathieu Luisier", email = "mluisier@iis.ee.ethz.ch" },
    { name = "Mauro Dossena", email = "mdossena@iis.ee.ethz.ch" },
    { name = "Nicolas Vetsch", email = "vetschn@iis.ee.ethz.ch" },
    { name = "Vincent Maillou", email = "vmaillou@iis.ee.ethz.ch" },
]
description = "Quantum Transport Simulations at the Exascale and Beyond"
license = { file = "LICENSE" }
classifiers = [
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Topic :: Scientific/Engineering",
]
keywords = ["Nano-TCAD", "Quantum Transport", "NEGF"]
dynamic = ["version"]
requires-python = ">=3.13"

dependencies = [
    "numpy>=2.3.0",
    "scipy>=1.16.0",
    "mpi4py>=4.1.0",
    "numba",
    "pydantic",
    "ase",
    "meshio",
    # gmsh wheels are not available for aarch64.
    "gmsh; platform_machine != 'aarch64'",
    "scikit-fem",
    "pyvista>=0.46.0",
    "matplotlib",
    "threadpoolctl",
    "typer",
    "h5py",
    "tomlkit",
]
    [project.optional-dependencies]
    dev = [
        "pytest",
        "pytest-cov",
        "pytest-mpi",
        "pytest-xdist",
        "coverage",
        "black",
        "blacken-docs",
        "isort",
        "ruff",
        "clang-format",
        "pre-commit",
        "ipykernel",
        "ipympl",
    ]
    docs = ["zensical", "mkdocstrings-python", "griffe", "griffe-pydantic", "tabulate"]
    gpu = ["cupy>=14.1.0"]


[tool.pytest.ini_options]
addopts = ["--import-mode=importlib"]
testpaths = ["tests"]

[tool.coverage.run]
relative_files = true

[tool.isort]
profile = "black"

[tool.setuptools.package-data]
"*" = ["*.cu"]


# ==== Settings for pixi ===============================================
[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64"]

# mpi4py is not in the "common" feature because for the "hpc"
# environment we want to install it from source (i.e., from PyPI and
# no-binary) to ensure that it is linked against the system MPI library.
[tool.pixi.dependencies]
mpi4py = ">=4.1.0"

[tool.pixi.pypi-dependencies]
quatrex = { path = ".", editable = true }

[tool.pixi.environments]
default = { features = ["common"], solve-group = "dev" }
dev = { features = ["common", "dev"], solve-group = "dev" }
docs = { features = ["common", "docs"], solve-group = "dev" }

# Separate solve group for GPU dependencies to avoid complicated version
# resolution issues with the main environment.
gpu = { features = ["common", "gpu"], solve-group = "gpu" }

# This environment is used for GitHub CI/CD linting and testing, since
# the low-rank reference QTBM tests require pardiso to run.
ci = { features = ["common", "dev", "pardiso"], solve-group = "dev" }

hpc = { features = ["common", "hpc"], solve-group = "hpc", no-default-feature = true }

# --- Shared features --------------------------------------------------
[tool.pixi.feature.common]
# Assuming here that only the "hpc" environment will be used on aarch64.
platforms = ["linux-64"]

    [tool.pixi.feature.common.dependencies]
    numpy = ">=2.3.0"
    scipy = ">=1.16.0"
    numba = "*"
    pydantic = "*"
    threadpoolctl = "*"
    ase = "*"
    meshio = "*"
    scikit-fem = "*"
    typer = "*"
    h5py = "*"
    gmsh = "*"
    python-gmsh = "*"    # conda-forge gmsh does not include python bindings
    pyvista = ">=0.46.0"
    matplotlib = "*"
    tomlkit = "*"

# --- Development features ---------------------------------------------
[tool.pixi.feature.dev]
platforms = ["linux-64"]

    [tool.pixi.feature.dev.dependencies]
    pytest = "*"
    pytest-cov = "*"
    pytest-mpi = "*"
    pytest-xdist = "*"
    coverage = "*"
    black = "*"
    blacken-docs = "*"
    isort = "*"
    ruff = "*"
    pre-commit = "*"
    ipykernel = "*"
    ipympl = "*"


# --- Documentation features -------------------------------------------
[tool.pixi.feature.docs.pypi-dependencies]
zensical = "*"
mkdocstrings-python = "*"
griffe = "*"
griffe-pydantic = "*"
tabulate = "*"
mike = { git = "https://github.com/squidfunk/mike.git" }

# --- GPU features -----------------------------------------------------
[tool.pixi.feature.gpu.dependencies]
cupy = ">=14.1.0"

# --- HPC features -----------------------------------------------------
[tool.pixi.feature.hpc]
platforms = ["linux-64", "linux-aarch64"]

    [tool.pixi.feature.hpc.pypi-dependencies]
    mpi4py = ">=4.1.0"
    cupy = ">=14.1.0"
    quatrex = { path = ".", editable = true }

    [tool.pixi.feature.hpc.pypi-options]
    no-binary = ["mpi4py"]

# --- Pardiso feature --------------------------------------------------
[tool.pixi.feature.pardiso]
dependencies = { pydiso = "*" }
platforms = ["linux-64"]


# --- Tasks ------------------------------------------------------------
[tool.pixi.tasks.test]
cmd = "pytest"
default-environment = "dev"
description = "Run the test suite with pytest. You can pass any arguments to pytest."

[tool.pixi.tasks.format]
cmd = """
isort --profile black . --skip .pixi/ \
&& black . \
&& blacken-docs \
&& clang-format -i $(find src/ -name "*.cu")
"""
default-environment = "dev"
description = "Format the code with isort, black, and clang-format."

[tool.pixi.tasks.lint]
cmd = "ruff check"
default-environment = "dev"
description = "Lint the code with ruff."

[tool.pixi.tasks.docs]
cmd = """
rm -rf docs/api/quatrex && rm -rf docs/api/qttools && rm -rf docs/user_guide/parameters \
&& python docs/scripts/generate_api_pages.py \
&& python docs/scripts/generate_parameter_docs.py \
&& zensical
"""
default-environment = "docs"
description = "Generate documentation and run zensical. Invoke with `serve` to serve the documentation locally."
